include_verbatim = false

exclude = [
    '^mailto:',
    '^tel:',
    '<email>',
    '<telegram>',
    '<session_id>',
    '<website>',
]

exclude_all_private = true

max_retries = 3
retry_wait_time = 5

timeout = 20

accept = ["100..=103", "200..=299", "300..=399"]